"""init_db

Revision ID: b2a7f08d12fa
Revises: 
Create Date: 2026-03-23 09:13:43.477897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from application.core.config import settings


# revision identifiers, used by Alembic.
revision: str = 'b2a7f08d12fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('login'),
    sa.UniqueConstraint('login'),
    schema=settings.POSTGRES_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###
